/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as MyUsageRouteImport } from './routes/my-usage'
import { Route as IndexRouteImport } from './routes/index'

const MyUsageRoute = MyUsageRouteImport.update({
  id: '/my-usage',
  path: '/my-usage',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/my-usage': typeof MyUsageRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/my-usage': typeof MyUsageRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/my-usage': typeof MyUsageRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/my-usage'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/my-usage'
  id: '__root__' | '/' | '/my-usage'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MyUsageRoute: typeof MyUsageRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/my-usage': {
      id: '/my-usage'
      path: '/my-usage'
      fullPath: '/my-usage'
      preLoaderRoute: typeof MyUsageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MyUsageRoute: MyUsageRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
